#!/bin/sh
ALIAS_CMD="$(echo ""$0"" | sed -e 's?/sbin/??')"

systemctl_exec() {
    if [ $# -eq 2 ]; then
        service $1 $2
    else
        exit 0
    fi
}

case "$ALIAS_CMD" in
    start|stop|restart|reload|status)
        trap "systemctl_exec $1 $ALIAS_CMD; exit 0" INT ABRT EXIT QUIT
        ;;
esac

if [ $# -eq 2 ]; then
    trap "systemctl_exec $2 $1; exit 0" INT ABRT EXIT QUIT
else
    exit 0
fi