#!/bin/bash
ALIAS_CMD="$(echo ""$0"" | sed -e 's?/sbin/??')"

systemctl_exec() {
    if [ $# -eq 2 ]; then
        cd /usr/lib/systemd/

        for f in $(find ./system ./user -name "$2.service")
        do
            case $1 in
                start)
                    CMD=$(while read line; do   if [[ $line =~ ^ExecStart=(.*)$ ]] ; then echo ${BASH_REMATCH[1]}; break; fi; done < $f)
                ;;
                stop)
                    CMD=$(while read line; do   if [[ $line =~ ^ExecStop=(.*)$ ]] ; then echo ${BASH_REMATCH[1]}; break; fi; done < $f)
                ;;
                reload)
                    CMD=$(while read line; do   if [[ $line =~ ^ExecReload=(.*)$ ]] ; then echo ${BASH_REMATCH[1]}; break; fi; done < $f)
                ;;
                \?)
                    exit 0
                ;;
            esac

            exec $CMD
            break
        done

    else
        exit 0
    fi
}

case "$ALIAS_CMD" in
    start|stop|restart|reload|status)
        trap "systemctl_exec $1 $ALIAS_CMD; exit 0" INT ABRT EXIT QUIT
        ;;
esac

if [ $# -eq 2 ]; then
    trap "systemctl_exec $1 $2; exit 0" INT ABRT EXIT QUIT
else
    exit 0
fi