#!/bin/sh
ALIAS_CMD="$(echo ""$0"" | sed -e 's?/sbin/??')"

service_exec() {
    if [ $# -eq 1 ]; then
        service_real $1
    elif [ $# -eq 2 ]; then
        service_real $1 $2
    else
        exit 0
    fi
}

case "$ALIAS_CMD" in
    start|stop|restart|reload|status)
        trap "service_exec $1 $ALIAS_CMD; exit 0" INT ABRT EXIT QUIT
        ;;
esac

if [ $# -eq 1 ]; then
    trap "service_exec $1; exit 0" INT ABRT EXIT QUIT
elif [ $# -eq 2 ]; then
    trap "service_exec $1 $2; exit 0" INT ABRT EXIT QUIT
else
    exit 0
fi